### PR TITLE
fix(mosaicod): pre 0.4.0 fixes

### LINKED ISSUE #406: Pre 0.4.0 release fixes
Misc fixes pre `v0.4.0` release:
- exit(-1) when server gets and error
- reformatted internal error 
- refactored database error to map a postgres code 23505 into an already esists error
- removed debug print of s3 credentials since it was exposing secret keys int the logs

### PR DESCRIPTION
**Pull request by cabba**
Closes #406

### CODE REVIEW

File: mosaicod/crates/mosaicod-db/src/error.rs [hunk 1]
```diff
@@ -1,36 +1,102 @@
...
+        }
+    }
+}
+
+impl From<sqlx::Error> for Error {
+    fn from(value: sqlx::Error) -> Self {
+        match &value {
+            sqlx::Error::Database(err) => {
+                if let Some(code) = err.code()
+                    && code == "23505"
```
Comment (DevMattG) [inline mosaicod/crates/mosaicod-db/src/error.rs]: Use sqlx::DatabaseError::is_unique_violation() instead of checking the code directly

**Review by DevMattG — CHANGES_REQUESTED** [review]

**Review by DevMattG — APPROVED** [review]
