### PR TITLE
Fixed `sequence_delete` action

### LINKED ISSUE #192: Foreign Key Constraint Violation When Executing SEQUENCE_DELETE Action
When sending the `do_action: SEQUENCE_DELETE` request, the backend returns a database error indicating a foreign key constraint violation. Specifically, the delete operation on table `sequence_t` fails because related records still exist in `session_t`, violating the constraint `session_t_sequence_id_fkey`.

**Error Message:**

```
facade error :: database error :: backend error :: 
error returned from database: 
update or delete on table "sequence_t" violates foreign key constraint 
"session_t_sequence_id_fkey" on table "session_t"
```

**Impact:**
The system does not allow deletion of a sequence if there are associated session records, and the error is not handled gracefully at the application level.

**Likely Cause:**
The backend attempts to delete a sequence without first deleting or handling dependent rows in `session_t`, and no cascading delete is configured for the foreign key relationship.

### PR DESCRIPTION
**Pull request by cabba**
Closes #192

### CODE REVIEW

**Comment by cabba** [comment]
I need to update cached queries in `.sqlx`

File: mosaicod/crates/mosaicod-facade/src/session.rs [hunk 1]
```diff
@@ -147,6 +143,10 @@ impl Session {
                     .notify(types::NotifyType::Error, msg.clone())
                     .await?,
             );
+        } else {
+            // This is done as last operation, otherwise multiple cals to this function will fail
```
Comment (DevMattG) [inline mosaicod/crates/mosaicod-facade/src/session.rs]: typo: cals -> calls

File: mosaicod/crates/mosaicod-facade/src/topic.rs [hunk 2]
```diff
@@ -323,10 +317,12 @@ impl Topic {
     }
 
     /// Permanently deletes a topic and all its data, be caution
+    ///
+    /// A [`types::DataLossToken`] is required since this call will lead to data losess.
```
Comment (DevMattG) [inline mosaicod/crates/mosaicod-facade/src/topic.rs]: typo: losess?

File: mosaicod/tests/src/actions.rs [hunk 3]
```diff
@@ -45,6 +45,34 @@ pub async fn sequence_create(
...
+            locator,
+        )
+        .into(),
+    };
+
+    dbg!(&action);
+
+    let mut stream = client.do_action(action).await.unwrap().into_inner();
+
+    while let Some(result) = stream.message().await.expect("Problem while streaming") {
```
Comment (DevMattG) [inline mosaicod/tests/src/actions.rs:66]: Is a while loop really needed here?

Comment (cabba) [reply mosaicod/tests/src/actions.rs:66]: Right now, I think removing the while will lead to the same behavior. However, I prefer to reach the end of the stream.
